export interface CountryCode {
	alpha2: string;
	alpha3: string;
	numeric: string;
	name: string;
}

export interface CurrencyCode {
	code: string;
	name: string;
	number: string;
	exponent: number;
}

export interface LanguageCode {
	code: string;
	name: string;
	native: string;
}

export const COUNTRIES: CountryCode[] = [
	{ alpha2: "AD", alpha3: "AND", numeric: "020", name: "Andorra" },
	{ alpha2: "AE", alpha3: "ARE", numeric: "784", name: "United Arab Emirates" },
	{ alpha2: "AF", alpha3: "AFG", numeric: "004", name: "Afghanistan" },
	{ alpha2: "AG", alpha3: "ATG", numeric: "028", name: "Antigua and Barbuda" },
	{ alpha2: "AL", alpha3: "ALB", numeric: "008", name: "Albania" },
	{ alpha2: "AM", alpha3: "ARM", numeric: "051", name: "Armenia" },
	{ alpha2: "AO", alpha3: "AGO", numeric: "024", name: "Angola" },
	{ alpha2: "AR", alpha3: "ARG", numeric: "032", name: "Argentina" },
	{ alpha2: "AT", alpha3: "AUT", numeric: "040", name: "Austria" },
	{ alpha2: "AU", alpha3: "AUS", numeric: "036", name: "Australia" },
	{ alpha2: "BD", alpha3: "BGD", numeric: "050", name: "Bangladesh" },
	{ alpha2: "BE", alpha3: "BEL", numeric: "056", name: "Belgium" },
	{ alpha2: "BG", alpha3: "BGR", numeric: "100", name: "Bulgaria" },
	{ alpha2: "BR", alpha3: "BRA", numeric: "076", name: "Brazil" },
	{ alpha2: "CA", alpha3: "CAN", numeric: "124", name: "Canada" },
	{ alpha2: "CH", alpha3: "CHE", numeric: "756", name: "Switzerland" },
	{ alpha2: "CL", alpha3: "CHL", numeric: "152", name: "Chile" },
	{ alpha2: "CN", alpha3: "CHN", numeric: "156", name: "China" },
	{ alpha2: "CO", alpha3: "COL", numeric: "170", name: "Colombia" },
	{ alpha2: "CZ", alpha3: "CZE", numeric: "203", name: "Czechia" },
	{ alpha2: "DE", alpha3: "DEU", numeric: "276", name: "Germany" },
	{ alpha2: "DK", alpha3: "DNK", numeric: "208", name: "Denmark" },
	{ alpha2: "EE", alpha3: "EST", numeric: "233", name: "Estonia" },
	{ alpha2: "EG", alpha3: "EGY", numeric: "818", name: "Egypt" },
	{ alpha2: "ES", alpha3: "ESP", numeric: "724", name: "Spain" },
	{ alpha2: "FI", alpha3: "FIN", numeric: "246", name: "Finland" },
	{ alpha2: "FR", alpha3: "FRA", numeric: "250", name: "France" },
	{ alpha2: "GB", alpha3: "GBR", numeric: "826", name: "United Kingdom" },
	{ alpha2: "GR", alpha3: "GRC", numeric: "300", name: "Greece" },
	{ alpha2: "HK", alpha3: "HKG", numeric: "344", name: "Hong Kong" },
	{ alpha2: "HR", alpha3: "HRV", numeric: "191", name: "Croatia" },
	{ alpha2: "HU", alpha3: "HUN", numeric: "348", name: "Hungary" },
	{ alpha2: "ID", alpha3: "IDN", numeric: "360", name: "Indonesia" },
	{ alpha2: "IE", alpha3: "IRL", numeric: "372", name: "Ireland" },
	{ alpha2: "IL", alpha3: "ISR", numeric: "376", name: "Israel" },
	{ alpha2: "IN", alpha3: "IND", numeric: "356", name: "India" },
	{ alpha2: "IR", alpha3: "IRN", numeric: "364", name: "Iran" },
	{ alpha2: "IS", alpha3: "ISL", numeric: "352", name: "Iceland" },
	{ alpha2: "IT", alpha3: "ITA", numeric: "380", name: "Italy" },
	{ alpha2: "JP", alpha3: "JPN", numeric: "392", name: "Japan" },
	{ alpha2: "KE", alpha3: "KEN", numeric: "404", name: "Kenya" },
	{ alpha2: "KR", alpha3: "KOR", numeric: "410", name: "Korea, Republic of" },
	{ alpha2: "KW", alpha3: "KWT", numeric: "414", name: "Kuwait" },
	{ alpha2: "LU", alpha3: "LUX", numeric: "442", name: "Luxembourg" },
	{ alpha2: "LV", alpha3: "LVA", numeric: "428", name: "Latvia" },
	{ alpha2: "MA", alpha3: "MAR", numeric: "504", name: "Morocco" },
	{ alpha2: "MX", alpha3: "MEX", numeric: "484", name: "Mexico" },
	{ alpha2: "MY", alpha3: "MYS", numeric: "458", name: "Malaysia" },
	{ alpha2: "NG", alpha3: "NGA", numeric: "566", name: "Nigeria" },
	{ alpha2: "NL", alpha3: "NLD", numeric: "528", name: "Netherlands" },
	{ alpha2: "NO", alpha3: "NOR", numeric: "578", name: "Norway" },
	{ alpha2: "NP", alpha3: "NPL", numeric: "524", name: "Nepal" },
	{ alpha2: "NZ", alpha3: "NZL", numeric: "554", name: "New Zealand" },
	{ alpha2: "PE", alpha3: "PER", numeric: "604", name: "Peru" },
	{ alpha2: "PH", alpha3: "PHL", numeric: "608", name: "Philippines" },
	{ alpha2: "PK", alpha3: "PAK", numeric: "586", name: "Pakistan" },
	{ alpha2: "PL", alpha3: "POL", numeric: "616", name: "Poland" },
	{ alpha2: "PT", alpha3: "PRT", numeric: "620", name: "Portugal" },
	{ alpha2: "QA", alpha3: "QAT", numeric: "634", name: "Qatar" },
	{ alpha2: "RO", alpha3: "ROU", numeric: "642", name: "Romania" },
	{ alpha2: "RS", alpha3: "SRB", numeric: "688", name: "Serbia" },
	{ alpha2: "RU", alpha3: "RUS", numeric: "643", name: "Russia" },
	{ alpha2: "SA", alpha3: "SAU", numeric: "682", name: "Saudi Arabia" },
	{ alpha2: "SE", alpha3: "SWE", numeric: "752", name: "Sweden" },
	{ alpha2: "SG", alpha3: "SGP", numeric: "702", name: "Singapore" },
	{ alpha2: "SI", alpha3: "SVN", numeric: "705", name: "Slovenia" },
	{ alpha2: "SK", alpha3: "SVK", numeric: "703", name: "Slovakia" },
	{ alpha2: "TH", alpha3: "THA", numeric: "764", name: "Thailand" },
	{ alpha2: "TR", alpha3: "TUR", numeric: "792", name: "Türkiye" },
	{ alpha2: "TW", alpha3: "TWN", numeric: "158", name: "Taiwan" },
	{ alpha2: "UA", alpha3: "UKR", numeric: "804", name: "Ukraine" },
	{ alpha2: "US", alpha3: "USA", numeric: "840", name: "United States" },
	{ alpha2: "VN", alpha3: "VNM", numeric: "704", name: "Viet Nam" },
	{ alpha2: "ZA", alpha3: "ZAF", numeric: "710", name: "South Africa" }
];

export const CURRENCIES: CurrencyCode[] = [
	{ code: "AED", name: "UAE Dirham", number: "784", exponent: 2 },
	{ code: "ARS", name: "Argentine Peso", number: "032", exponent: 2 },
	{ code: "AUD", name: "Australian Dollar", number: "036", exponent: 2 },
	{ code: "BHD", name: "Bahraini Dinar", number: "048", exponent: 3 },
	{ code: "BRL", name: "Brazilian Real", number: "986", exponent: 2 },
	{ code: "CAD", name: "Canadian Dollar", number: "124", exponent: 2 },
	{ code: "CHF", name: "Swiss Franc", number: "756", exponent: 2 },
	{ code: "CLP", name: "Chilean Peso", number: "152", exponent: 0 },
	{ code: "CNY", name: "Chinese Yuan", number: "156", exponent: 2 },
	{ code: "COP", name: "Colombian Peso", number: "170", exponent: 2 },
	{ code: "CZK", name: "Czech Koruna", number: "203", exponent: 2 },
	{ code: "DKK", name: "Danish Krone", number: "208", exponent: 2 },
	{ code: "EGP", name: "Egyptian Pound", number: "818", exponent: 2 },
	{ code: "EUR", name: "Euro", number: "978", exponent: 2 },
	{ code: "GBP", name: "Pound Sterling", number: "826", exponent: 2 },
	{ code: "HKD", name: "Hong Kong Dollar", number: "344", exponent: 2 },
	{ code: "HUF", name: "Hungarian Forint", number: "348", exponent: 2 },
	{ code: "IDR", name: "Indonesian Rupiah", number: "360", exponent: 2 },
	{ code: "ILS", name: "Israeli Shekel", number: "376", exponent: 2 },
	{ code: "INR", name: "Indian Rupee", number: "356", exponent: 2 },
	{ code: "JPY", name: "Japanese Yen", number: "392", exponent: 0 },
	{ code: "KRW", name: "South Korean Won", number: "410", exponent: 0 },
	{ code: "KWD", name: "Kuwaiti Dinar", number: "414", exponent: 3 },
	{ code: "MXN", name: "Mexican Peso", number: "484", exponent: 2 },
	{ code: "MYR", name: "Malaysian Ringgit", number: "458", exponent: 2 },
	{ code: "NOK", name: "Norwegian Krone", number: "578", exponent: 2 },
	{ code: "NZD", name: "New Zealand Dollar", number: "554", exponent: 2 },
	{ code: "PHP", name: "Philippine Peso", number: "608", exponent: 2 },
	{ code: "PLN", name: "Polish Zloty", number: "985", exponent: 2 },
	{ code: "QAR", name: "Qatari Riyal", number: "634", exponent: 2 },
	{ code: "RON", name: "Romanian Leu", number: "946", exponent: 2 },
	{ code: "RUB", name: "Russian Ruble", number: "643", exponent: 2 },
	{ code: "SAR", name: "Saudi Riyal", number: "682", exponent: 2 },
	{ code: "SEK", name: "Swedish Krona", number: "752", exponent: 2 },
	{ code: "SGD", name: "Singapore Dollar", number: "702", exponent: 2 },
	{ code: "THB", name: "Thai Baht", number: "764", exponent: 2 },
	{ code: "TRY", name: "Turkish Lira", number: "949", exponent: 2 },
	{ code: "TWD", name: "New Taiwan Dollar", number: "901", exponent: 2 },
	{ code: "UAH", name: "Ukrainian Hryvnia", number: "980", exponent: 2 },
	{ code: "USD", name: "US Dollar", number: "840", exponent: 2 },
	{ code: "VND", name: "Vietnamese Dong", number: "704", exponent: 0 },
	{ code: "ZAR", name: "South African Rand", number: "710", exponent: 2 }
];

export const LANGUAGES: LanguageCode[] = [
	{ code: "ar", name: "Arabic", native: "العربية" },
	{ code: "bn", name: "Bengali", native: "বাংলা" },
	{ code: "cs", name: "Czech", native: "Čeština" },
	{ code: "da", name: "Danish", native: "Dansk" },
	{ code: "de", name: "German", native: "Deutsch" },
	{ code: "el", name: "Greek", native: "Ελληνικά" },
	{ code: "en", name: "English", native: "English" },
	{ code: "es", name: "Spanish", native: "Español" },
	{ code: "fa", name: "Persian", native: "فارسی" },
	{ code: "fi", name: "Finnish", native: "Suomi" },
	{ code: "fr", name: "French", native: "Français" },
	{ code: "he", name: "Hebrew", native: "עברית" },
	{ code: "hi", name: "Hindi", native: "हिन्दी" },
	{ code: "hu", name: "Hungarian", native: "Magyar" },
	{ code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
	{ code: "it", name: "Italian", native: "Italiano" },
	{ code: "ja", name: "Japanese", native: "日本語" },
	{ code: "ko", name: "Korean", native: "한국어" },
	{ code: "ms", name: "Malay", native: "Bahasa Melayu" },
	{ code: "nl", name: "Dutch", native: "Nederlands" },
	{ code: "no", name: "Norwegian", native: "Norsk" },
	{ code: "pl", name: "Polish", native: "Polski" },
	{ code: "pt", name: "Portuguese", native: "Português" },
	{ code: "ro", name: "Romanian", native: "Română" },
	{ code: "ru", name: "Russian", native: "Русский" },
	{ code: "sv", name: "Swedish", native: "Svenska" },
	{ code: "th", name: "Thai", native: "ไทย" },
	{ code: "tr", name: "Turkish", native: "Türkçe" },
	{ code: "uk", name: "Ukrainian", native: "Українська" },
	{ code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
	{ code: "zh", name: "Chinese", native: "中文" }
];
