export interface PortEntry {
	port: number;
	protocol: "tcp" | "udp" | "tcp/udp";
	service: string;
	description: string;
}

export const PORTS: PortEntry[] = [
	{ port: 20, protocol: "tcp", service: "ftp-data", description: "FTP data transfer" },
	{ port: 21, protocol: "tcp", service: "ftp", description: "FTP control" },
	{ port: 22, protocol: "tcp", service: "ssh", description: "Secure Shell / SCP / SFTP" },
	{ port: 23, protocol: "tcp", service: "telnet", description: "Telnet (insecure)" },
	{ port: 25, protocol: "tcp", service: "smtp", description: "SMTP — mail relay" },
	{ port: 53, protocol: "tcp/udp", service: "dns", description: "Domain Name System" },
	{ port: 67, protocol: "udp", service: "dhcp", description: "DHCP server" },
	{ port: 68, protocol: "udp", service: "dhcp", description: "DHCP client" },
	{ port: 69, protocol: "udp", service: "tftp", description: "Trivial File Transfer" },
	{ port: 80, protocol: "tcp", service: "http", description: "HTTP" },
	{ port: 88, protocol: "tcp/udp", service: "kerberos", description: "Kerberos authentication" },
	{ port: 110, protocol: "tcp", service: "pop3", description: "Post Office Protocol 3" },
	{ port: 111, protocol: "tcp/udp", service: "rpcbind", description: "Sun ONC/RPC portmapper" },
	{ port: 119, protocol: "tcp", service: "nntp", description: "Network News Transfer" },
	{ port: 123, protocol: "udp", service: "ntp", description: "Network Time Protocol" },
	{ port: 135, protocol: "tcp", service: "msrpc", description: "Microsoft RPC" },
	{ port: 137, protocol: "udp", service: "netbios-ns", description: "NetBIOS Name Service" },
	{ port: 138, protocol: "udp", service: "netbios-dgm", description: "NetBIOS Datagram" },
	{ port: 139, protocol: "tcp", service: "netbios-ssn", description: "NetBIOS Session" },
	{ port: 143, protocol: "tcp", service: "imap", description: "IMAP" },
	{ port: 161, protocol: "udp", service: "snmp", description: "SNMP" },
	{ port: 162, protocol: "udp", service: "snmptrap", description: "SNMP trap" },
	{ port: 179, protocol: "tcp", service: "bgp", description: "Border Gateway Protocol" },
	{ port: 194, protocol: "tcp", service: "irc", description: "Internet Relay Chat" },
	{ port: 389, protocol: "tcp/udp", service: "ldap", description: "LDAP" },
	{ port: 443, protocol: "tcp", service: "https", description: "HTTPS" },
	{ port: 445, protocol: "tcp", service: "smb", description: "SMB / CIFS" },
	{ port: 465, protocol: "tcp", service: "smtps", description: "SMTP over TLS (legacy)" },
	{ port: 514, protocol: "udp", service: "syslog", description: "Syslog" },
	{ port: 515, protocol: "tcp", service: "lpd", description: "Line Printer Daemon" },
	{ port: 587, protocol: "tcp", service: "submission", description: "SMTP submission" },
	{ port: 631, protocol: "tcp/udp", service: "ipp", description: "Internet Printing Protocol" },
	{ port: 636, protocol: "tcp", service: "ldaps", description: "LDAP over TLS" },
	{ port: 853, protocol: "tcp", service: "dns-over-tls", description: "DNS over TLS" },
	{ port: 873, protocol: "tcp", service: "rsync", description: "rsync" },
	{ port: 989, protocol: "tcp", service: "ftps-data", description: "FTPS data" },
	{ port: 990, protocol: "tcp", service: "ftps", description: "FTPS control" },
	{ port: 993, protocol: "tcp", service: "imaps", description: "IMAP over TLS" },
	{ port: 995, protocol: "tcp", service: "pop3s", description: "POP3 over TLS" },
	{ port: 1080, protocol: "tcp", service: "socks", description: "SOCKS proxy" },
	{ port: 1194, protocol: "udp", service: "openvpn", description: "OpenVPN" },
	{ port: 1433, protocol: "tcp", service: "mssql", description: "Microsoft SQL Server" },
	{ port: 1521, protocol: "tcp", service: "oracle", description: "Oracle Database" },
	{ port: 1701, protocol: "udp", service: "l2tp", description: "L2TP VPN" },
	{ port: 1723, protocol: "tcp", service: "pptp", description: "PPTP VPN" },
	{ port: 1812, protocol: "udp", service: "radius", description: "RADIUS authentication" },
	{ port: 2049, protocol: "tcp/udp", service: "nfs", description: "Network File System" },
	{ port: 2375, protocol: "tcp", service: "docker", description: "Docker daemon (insecure)" },
	{ port: 2376, protocol: "tcp", service: "docker-tls", description: "Docker daemon (TLS)" },
	{ port: 3000, protocol: "tcp", service: "node", description: "Common Node.js dev server" },
	{ port: 3306, protocol: "tcp", service: "mysql", description: "MySQL / MariaDB" },
	{ port: 3389, protocol: "tcp", service: "rdp", description: "Remote Desktop Protocol" },
	{ port: 4444, protocol: "tcp", service: "metasploit", description: "Common Meterpreter / dev" },
	{ port: 5000, protocol: "tcp", service: "upnp", description: "UPnP / Flask dev server" },
	{ port: 5060, protocol: "tcp/udp", service: "sip", description: "SIP signaling" },
	{ port: 5432, protocol: "tcp", service: "postgresql", description: "PostgreSQL" },
	{ port: 5672, protocol: "tcp", service: "amqp", description: "AMQP / RabbitMQ" },
	{ port: 5900, protocol: "tcp", service: "vnc", description: "VNC display 0" },
	{ port: 5984, protocol: "tcp", service: "couchdb", description: "CouchDB" },
	{ port: 6379, protocol: "tcp", service: "redis", description: "Redis" },
	{ port: 6443, protocol: "tcp", service: "kubernetes-api", description: "Kubernetes API server" },
	{ port: 7000, protocol: "tcp", service: "cassandra", description: "Cassandra inter-node" },
	{ port: 7001, protocol: "tcp", service: "cassandra-tls", description: "Cassandra inter-node TLS" },
	{ port: 8000, protocol: "tcp", service: "http-alt", description: "Common dev / Django" },
	{ port: 8080, protocol: "tcp", service: "http-proxy", description: "HTTP alternate / proxy" },
	{ port: 8081, protocol: "tcp", service: "http-alt", description: "HTTP alternate" },
	{ port: 8443, protocol: "tcp", service: "https-alt", description: "HTTPS alternate" },
	{ port: 8888, protocol: "tcp", service: "http-alt", description: "Common dev (Jupyter)" },
	{ port: 9000, protocol: "tcp", service: "php-fpm", description: "PHP-FPM / SonarQube / dev" },
	{ port: 9090, protocol: "tcp", service: "prometheus", description: "Prometheus / dev" },
	{ port: 9200, protocol: "tcp", service: "elasticsearch", description: "Elasticsearch HTTP" },
	{ port: 9300, protocol: "tcp", service: "elasticsearch-tx", description: "Elasticsearch transport" },
	{ port: 9418, protocol: "tcp", service: "git", description: "Git protocol" },
	{ port: 9999, protocol: "tcp", service: "abyss", description: "Common dev / Abyss" },
	{ port: 11211, protocol: "tcp/udp", service: "memcached", description: "Memcached" },
	{ port: 25565, protocol: "tcp", service: "minecraft", description: "Minecraft Java server" },
	{ port: 27017, protocol: "tcp", service: "mongodb", description: "MongoDB" }
];
